# Generated by Django 4.2.5 on 2023-11-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_tags',
            field=models.ManyToManyField(null=True, to='administracion.tag', verbose_name='Tags'),
        ),
    ]
