# Generated by Django 4.2.5 on 2023-11-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_tags',
            field=models.ManyToManyField(to='administracion.tag', verbose_name='Tags'),
        ),
    ]
